### ISSUE TITLE
Tracer purity correction

### ISSUE THREAD

**Issue by XiaoyangSu** [MetaSys-LISBP/IsoCor#12] opened 2019-04-30 17:34 UTC
I have encountered some unexpected results in the correction. I have the input data for unlabeled Acetyl-CoA (assuming this is a 15N experiment). If I turn on the tracer purity option and set 15N to 100%, I got the correct answer that AcCoA is unlabeled. However, if I do not turn on the tracer purity option, the results show 2.5% 15N-1 labeled fraction.
Because the AcCoA is unlabeled, theoretically the tracer purity should not play a role. I'm assuming leaving the tracer purity correction off means 100% 15N, but the results are different.   
An easy fix would be to turn on the tracer correction by default. But I'm curious what causes the differences mathematically. 
Please see the output and log files w/ or w/o tracer purity correction.

[AcCoA_TracerCorrection.zip](https://github.com/MetaSys-LISBP/IsoCor/files/3132401/AcCoA_TracerCorrection.zip)

**Comment by pierremillard** [comment] 2019-05-02 08:36
Dear @XiaoyangSu ,

thanks for having attached the input data files and the logs.

When correcting these data using the following options:

- correction of natural abundance of the tracer : no
- tracer purity set to 100%

the 15N1 fraction is indeed about 2.5%. The mean enrichment is estimated to be 0.00385, i.e. close to the natural abundance of 15N (0.00364), as expected.

In this situation where the mass fractions to be corrected correspond to an unlabeled metabolite (i.e. at natural abundance), activating the correction for tracer purity should have virtually no impact, which is actually the case (15N1 is still at 2.5% with a purity of 99%). 

When activating the correction for natural abundance of the tracer (wih the tracer purity at 100%), I get a 15N1 fraction (and mean enrichment) close to 0, which is the expected result. When also activating the correction for tracer purity (set at 99% for example), here again the results barely change (the difference in 15N is lower than 1.e-5), which is also expected.

Actually you might not have got the point of the options: "Correct natural abundance of the tracer" is not related to the purity, but to the correction of natural abundance brought by the tracer element (here 15N). To correct for the tracer purity, you should not check the box "Correct natural abundance of the tracer", you just have to change the abundance of each tracer isotope in the "Isotopic purity of the tracer" box. These two correction options are decoupled because depending on the data integration pipeline (e.g. for flux calculation), we might want (or not) correct for natural abundance of the tracer element and/or for purity of the tracer. We had a long standing debate on the default correction options. We think that the best option is to correct both for natural abundance of the tracer element and for purity of the tracer, however since we cannot know the purity beforehand (it depends on the isotopic tracer and on the provider of labeled metabolites, and thus depends on each experiment), we have prefered to not apply any correction for the tracer element by default (i.e. no correction for purity and no correction for natural abundance). Detailed information on which correction options should be selected can be found in a dedicated section of isocor documentation ([here](https://isocor.readthedocs.io/en/latest/tutorials.html#isotopic-purity-and-natural-abundance-of-the-tracer)), with several examples for practical considerations.

Isocor has the expected behaviour with your dataset, no need of fix :)

Let me know if this is clear now. If everything is ok to you, please could you close this issue? Otherwise, let us know what we should clarified.

**Comment by XiaoyangSu** [comment] 2019-05-02 15:12
I see. Sorry I had some misunderstanding on the tracer element natural abundance correction option. This is to correct the tracer abundance, not tracer purity. AcCoA for example, unlabeled AcCoA will give 19.5% M+1 is this option is unchecked, which is exactly the expected natural abundance of 13C.
Even though I can't think of an application where the tracer natural abundance should not be corrected, I agree leaving this an option offers greater flexibility. Thank you for the explanation!!

**Comment by pierremillard** [comment] 2019-05-03 07:43
No worries @XiaoyangSu ! We agree that correcting only for purity or natural abundance of the tracer is not classicaly part of current integration pipelines, but this flexibility offers the possibility to apply custom correction for new applications that would require such feature.
We think this feature might still be valuable with current applications in specific situations. For instance, if the purity is not accurately known, this still lets users the possibility to correct only for natural abundance of the tracer (and this could be a straightforward way to estimate the isotopic purity of the label input). If these data are used for flux calculation, purity could then be an additional parameter to be estimated in isotopic flux models.

**Closed as completed by pierremillard** 2019-05-03 07:43 UTC
Labels: question
